version: '3.8'

services:
  intern:
    image: "${ECR_URL}:latest"
    container_name: intern-server
    ports:
      - "8080:8080"
    env_file:
      - /home/ubuntu/intern-server/.env
    environment:
      DB_LINK: ${DB_LINK}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
